"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const string_js_1 = require("./helpers/string.js");
const date_js_1 = require("./helpers/date.js");
const meta_js_1 = require("./helpers/meta.js");
const util_js_1 = require("./helpers/util.js");
const content_js_1 = require("./filters/content.js");
const search_js_1 = require("./generators/search.js");
const _404_js_1 = require("./generators/404.js");
const note_js_1 = require("./tags/note.js");
const image_js_1 = require("./tags/image.js");
const quote_js_1 = require("./tags/quote.js");
const tabs_js_1 = require("./tags/tabs.js");
const details_js_1 = require("./tags/details.js");
const linkCard_js_1 = require("./tags/linkCard.js");
const postLinkCard_js_1 = require("./tags/postLinkCard.js");
// Enable hljs-prefixed CSS class names so our syntax highlighting CSS can target tokens.
hexo.config.highlight.hljs = true;
(0, string_js_1.registerStringHelpers)(hexo);
(0, date_js_1.registerDateHelpers)(hexo);
(0, meta_js_1.registerMetaHelpers)(hexo);
(0, util_js_1.registerUtilHelpers)(hexo);
(0, content_js_1.registerContentFilters)(hexo);
(0, search_js_1.registerSearchGenerator)(hexo);
(0, _404_js_1.register404Generator)(hexo);
(0, note_js_1.registerNoteTag)(hexo);
(0, image_js_1.registerImageTag)(hexo);
(0, quote_js_1.registerQuoteTag)(hexo);
(0, tabs_js_1.registerTabsTag)(hexo);
(0, details_js_1.registerDetailsTag)(hexo);
(0, linkCard_js_1.registerLinkCardTag)(hexo);
(0, postLinkCard_js_1.registerPostLinkCardTag)(hexo);
