"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerSearchGenerator = registerSearchGenerator;
function registerSearchGenerator(hexo) {
    hexo.extend.generator.register('search', function (locals) {
        if (!hexo.theme.config?.search?.enable)
            return;
        const posts = locals.posts.filter((p) => p.published !== false).toArray();
        const pages = (locals.pages || { filter: () => ({ toArray: () => [] }) })
            .filter((p) => p.published !== false)
            .toArray();
        const mapEntry = (item, type) => {
            // Build a clean excerpt: prefer the post's own excerpt (auto-generated by Hexo
            // from <!-- more --> or first ~100 words), fall back to stripping content.
            const rawExcerpt = item.excerpt || item.content || '';
            const excerpt = rawExcerpt
                .replace(/<[^>]*>/g, '')
                .replace(/\s+/g, ' ')
                .trim()
                .slice(0, 160); // keep search.json compact
            return {
                title: item.title,
                excerpt,
                url: item.permalink ||
                    '/' + (item.path || ''),
                categories: item.categories?.data?.map((c) => c.name) || [],
                tags: item.tags?.data?.map((t) => t.name) || [],
                type,
            };
        };
        const index = [
            ...posts.map((p) => mapEntry(p, 'post')),
            ...pages.map((p) => mapEntry(p, 'page')),
        ];
        return {
            path: 'search.json',
            data: JSON.stringify(index),
        };
    });
}
